# Generated by Django 3.0.4 on 2020-03-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='last_modify',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
