# Generated by Django 3.0.4 on 2020-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200326_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='last_modify',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
