# Generated by Django 3.0.4 on 2020-03-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
