# Generated by Django 3.0.4 on 2020-03-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200328_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='last_search',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
